name: MCGems
version: '${version}'
main: me.bscal.mcgems.MCGems
api-version: 1.19
libraries:
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.2"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.2"
  - "io.github.rysefoxx.inventory:RyseInventory-Plugin:1.5.4"